https://en.wikibooks.org/wiki/Java_Programming/Throwing_and_Catching_Exceptions#try/catch_statement
Throwing and Catching Exceptions - try/catch statement
By default, when an exception is thrown, the current method is interrupted, the calling method is interrupted too and so on till the main method. A thrown exception can also be caught using a try/catch statement. Below is how a try/catch statement works:The executed code lines have been highlighted. When no exception is thrown, the method flow executes the try statement and not the catch statement.As there is a thrown exception at line 5, the line 6 is not executed, but the exception is caught by the catch statement so the catch block is executed. The following code is also executed. Note that the catch statement takes an exception as parameter. There is a third case: when the exception is not from the same class as the parameter:It is as if there is no try/catch statement. The exception is thrown to the calling method.